### PR TITLE
--ambiguous includes a symlink to a file as ambiguous to that file

### PR DESCRIPTION
**Pull request by snandan**
In my test case './include/a.h' is a symbolic link to './src/a.h'. I am getting the following message with '--ambiguous'. I assume there should not be any message.

```
Found 1 ambiguous includes

Include for a.h
Found in : 
  included from ./src/a.cpp
Options for file: 
  ./include/a.h
  ./src/a.h

```

### CODE REVIEW

**Comment by snandan** [comment]
Sorry, Can you just integrate 'Use canonical file names', e163219. I did not meant the other checkins to go.
I don't know if there is any way for me to change that now. I am not a git expert.

**Comment by dascandy** [comment]
I'll run a test on Monday to check how much this impacts performance. While I am in favor of having it be correct, it shouldn't be correct at the expense of being usable on huge projects.

**Comment by dascandy** [comment]
In case you do have a symlink this causes the paths to change so your change causes it to crash. Did you test it?

Additionally, I would argue that a user or other IDE will be equally confused which of those files you actually meant. You have include paths to fix this, symlinks should not be needed (and not used). Based on that I prefer the current behaviour over treating symlinks as an alternate path to the target file.

**Comment by dascandy** [comment]
Closing pull request as it does not work after this change, and the change itself is hard to explain. Will add entry in documentation about this issue.

**Pull request closed without merging**
