### PR TITLE
Add CMake build configuration for cpp-dependencies itself

### PR DESCRIPTION
**Pull request by torbjoernk**
I was annoyed by the fact that I had to modify and patch the Visual Studio solution/project files manually each time I tested cpp-dependencies on a different machine or did a clean git checkout. I had to adjust the paths to Boost in two places (include path and library path) as well as I had to switch the toolset (v120 is pre-selected in the solution file, I've only v140 installed) and consequently had to modify the Boost library names.

I've written simple CMakeLists files to let CMake generate the build instructions (GNU make, MSBuild/Visual Studio).
The location of Boost::filesystem (and the implicitly dependent Boost::system) is detected by CMake. People having Boost in a non-default location can use `-DBOOST_ROOT=<BOOST_PREFIX_PATH>` to tell CMake to preferably search in the given path for Boost headers and libraries.
With an optional argument `-DWITH_TESTS=OFF` one can skip the creation of the `unittest` target.

To ease building the unit tests, I've added GTest as a Git submodule and link the `unittest` target to the `gtest_main` target.

The following targets are created for _Debug_, _Release_ and _RelWithDebInfo_ configurations:
- `cpp_dependencies_obj`
  all source files, except `main.cpp`
- `cpp-dependencies`
  the actual executable
- if `WITH_TESTS=ON` (the default)
  - `gtest_main`
    GoogleTest static library
  - `unittests`
    cpp-dependencies' unittests

I have deleted the existing build scripts and solution files.

I have tested this
- on a Linux machine (openSUSE 42.1) with CMake 3.6.1, GCC 6.2.1 and Boost 1.54.0
- on a Windows 7 64bit machine with CMake 3.5, Visual Studio 2015 Update 3 (v140 toolchain) and Boost 1.61.0

ToDo:
- [ ] adjust Travis configuration

### CODE REVIEW

**Comment by torbjoernk** [comment]
Still got a bug in the Travis. It's overwriting the `CXX` and `CC` variables. Don't know how to fix that right now. :cry:

**Comment by dascandy** [comment]
Is that last bug you mentioned now fixed? As far as I can tell Travis at least works - but I'm not sure if that means it's correct now.

Looks like it's testing GCC 4.8.4 4 times now. Let me see if I can find a fix for that...

**Comment by torbjoernk** [comment]
@dascandy Unfortunately, it's not fixed. Travis is running without failures, however, it's not using the configured compilers but GCC 4.9 all the time. As said, I've no idea how to fix that.

**Comment by dascandy** [comment]
Found it. Apparently, if you have a  "compiler: " at the top of your travis config, it'll export CC and CXX for you, overriding whatever you would want to put in there. Removing this and putting it per-item in the matrix causes it to think you're using GCC for Ruby (????) - but it does stop overriding CC and CXX. Will import your PR into a branch and merge it sometime later. Thanks!

**Comment by dascandy** [comment]
I've pulled your changes manually to my own dev branch and updated it to match the other changes. Sorry that I didn't integrate your change directly. It is in now, and you should be able to use it as you did your branch. The BOOST_ROOT may not work yet, I think I may have broken that.

Major thanks for the work you did though, starting from this point was much less work than doing it from scratch.

**Pull request closed without merging**
